var appCL =
  '<p class="B C">TODO</p> '
+ '<ul><li>Test out surround sound somehow - Chrome defaults to stereo at the moment.'
+ '</li></ul>'
+ 'If you find a bug, or have a suggestion, please let me know at '
+ '<a class=ubLink href="https://github.com/StewVed/audiotester/issues" target=_blank>GitHub Issues</a>'
+ '<hr>'
+ '<p class="B C">18th September 2019</p> '
+ '<ul><li>' + zDev + 'A few more adjustments here and there for the latest developments to the global files.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">2nd April 2017</p> '
+ '<ul><li>' + zDev + 'A few adjustments here and there for the latest developments to the global files.'
+ '</li></ul>'
+ '<hr>'
+ '<p class="B C">3rd March 2017</p> '
+ '<ul><li>' + zNew + 'New app based on a combination of the Tone Generator of my Webtop, and my CaloieCalculator project (which has the latest code).'
+ '</li></ul>'
+ '<hr>'
;
